// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzmavggqpmlpxaispkta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bWF2Z2dxcG1scHhhaXNwa3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzc1NzEsImV4cCI6MjA2Nzk1MzU3MX0.lsM0eQ6c58N0ARg-bsWykx6NDKFleOQOWn4Tpuxw9WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});